name: Process Updated Articles

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Trigger manually via the GitHub UI

jobs:
  process_articles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run script to process articles
        env:
          #NOCO_BASE_URL: ${{ secrets.https://app.nocodb.com }}  # Set NocoDB base URL as secret
          API_KEY: ${{ secrets.OXUxBBtiQQZDELL51Hg2p6zlqrs_KUIRGze21z-w }}         # Set API Key as secret
          MAIN_ARTICLES_TABLE: "m3ocvzfbhk8ahk1"         # Name of the main articles table
          TRANSLATIONS_TABLE: "mr422qhi3kt0r4h"  # Name of the translations table
          LANGUAGES_TABLE: "mhuq2qb2ur6vkgn"                # Name of the languages table
        run: |
          python process_articles.py
